"""Deterministic synthetic predictions, for validating the pipeline end to end.

These are **not model outputs and must never be reported as results.** They exist
so that the whole chain — evaluation, sensitivity sweep, figures, HTML report —
can be exercised and debugged on a CPU before any GPU time is spent, and so that
CI can test the report pipeline without shipping a checkpoint.

Every artefact produced from them is stamped ``synthetic: true`` and the report
renders a banner. The generator is seeded and its degradation profiles are
declared explicitly, so a given profile always produces the same masks.

The profiles are shaped to imitate failure modes actually observed in the source
notebooks — in particular a model with high pixel accuracy that never recovers a
pedestrian, a pole or a sign — because a pipeline that has only ever been run on
well-behaved inputs has not really been tested.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field

import numpy as np

from .taxonomy import CLASS_NAMES, IGNORE_INDEX, NUM_CLASSES, class_index

__all__ = ["DegradationProfile", "PROFILES", "degrade", "SYNTHETIC_WARNING"]

SYNTHETIC_WARNING = (
    "SYNTHETIC pipeline fixture — generated by drivemetrics.synthetic, not a "
    "trained model. Any number derived from it describes the generator, not "
    "segmentation performance."
)


def _erode(mask: np.ndarray, iterations: int) -> np.ndarray:
    """Binary erosion with 4-connectivity, implemented with array shifts.

    Hand-rolled rather than taken from scipy so that the fixture generator adds
    no dependency to a package whose whole point is being installable and
    testable with numpy alone.
    """
    out = mask
    for _ in range(max(0, iterations)):
        keep = out.copy()
        keep[1:, :] &= out[:-1, :]
        keep[:-1, :] &= out[1:, :]
        keep[:, 1:] &= out[:, :-1]
        keep[:, :-1] &= out[:, 1:]
        # Anything touching the border erodes inward too, so that objects
        # entering frame degrade the way a real model degrades them.
        keep[0, :] = False
        keep[-1, :] = False
        keep[:, 0] = False
        keep[:, -1] = False
        out = keep
    return out


def _dilate(mask: np.ndarray, iterations: int) -> np.ndarray:
    out = mask
    for _ in range(max(0, iterations)):
        grown = out.copy()
        grown[1:, :] |= out[:-1, :]
        grown[:-1, :] |= out[1:, :]
        grown[:, 1:] |= out[:, :-1]
        grown[:, :-1] |= out[:, 1:]
        out = grown
    return out


@dataclass(frozen=True)
class DegradationProfile:
    """How one synthetic 'model' fails.

    ``drop``
        Classes the model never predicts at all. Their pixels are relabelled to
        ``confused_with``. This reproduces the observed IoU-of-0.0000 case.
    ``erode``
        Per-class boundary erosion in pixels — the ordinary under-segmentation
        of small objects. Eroded-away pixels go to ``confused_with``.
    ``dilate``
        Per-class growth, for imitating a model biased toward over-calling a
        class. Applied after erosion and allowed to overwrite other classes.
    ``confused_with``
        Where a class's lost pixels go. Defaults to Road.
    """

    name: str
    description: str
    drop: tuple = ()
    erode: Mapping[int, int] = field(default_factory=dict)
    dilate: Mapping[int, int] = field(default_factory=dict)
    confused_with: Mapping[int, int] = field(default_factory=dict)
    #: Fraction of remaining pixels flipped to a random class, to keep the
    #: confusion matrix from being unrealistically clean.
    noise: float = 0.0

    def fill_for(self, cls: int) -> int:
        return self.confused_with.get(cls, class_index("Road"))


_SKY = class_index("Sky")
_TREE = class_index("Tree")
_FENCE = class_index("Fence")
_ROAD = class_index("Road")
_BUILDING = class_index("Building")
_PAVEMENT = class_index("Pavement")
_POLE = class_index("Pole")
_SIGN = class_index("SignSymbol")
_PED = class_index("Pedestrian")
_BIC = class_index("Bicyclist")
_CAR = class_index("Car")


PROFILES: dict[str, DegradationProfile] = {
    "synth-background-biased": DegradationProfile(
        name="synth-background-biased",
        description=(
            "High pixel accuracy, blind to small hazards. Imitates the observed "
            "DeepLabV3 run: Pole, SignSymbol and Pedestrian never recovered."
        ),
        drop=(_POLE, _SIGN, _PED),
        erode={_BIC: 3, _CAR: 2, _PAVEMENT: 1},
        confused_with={_POLE: _BUILDING, _SIGN: _BUILDING, _PED: _BUILDING, _BIC: _ROAD},
        noise=0.005,
    ),
    "synth-balanced": DegradationProfile(
        name="synth-balanced",
        description=(
            "Moderate under-segmentation everywhere, nothing dropped. Lower "
            "background scores than the biased profile but keeps the hazards."
        ),
        erode={_POLE: 1, _SIGN: 1, _PED: 1, _BIC: 1, _CAR: 1, _BUILDING: 2, _ROAD: 1},
        confused_with={_POLE: _BUILDING, _SIGN: _BUILDING, _PED: _BUILDING},
        noise=0.02,
    ),
    "synth-hazard-priority": DegradationProfile(
        name="synth-hazard-priority",
        description=(
            "Recovers hazards almost perfectly but is sloppy on background "
            "boundaries — the profile a heavily class-rebalanced or focal-loss "
            "model tends to produce. Scores marginally *worse* than "
            "synth-background-biased on mIoU while recovering roughly twice as "
            "many VRU pixels. This is the rank inversion the package exists to "
            "expose, and it is here so that codepath is exercised by CI."
        ),
        erode={
            _SKY: 8,
            _BUILDING: 8,
            _ROAD: 8,
            _PAVEMENT: 8,
            _TREE: 8,
            _FENCE: 8,
            _CAR: 2,
        },
        confused_with={
            _SKY: _BUILDING,
            _BUILDING: _ROAD,
            _ROAD: _PAVEMENT,
            _PAVEMENT: _ROAD,
            _TREE: _BUILDING,
            _FENCE: _BUILDING,
            _CAR: _ROAD,
        },
        noise=0.02,
    ),
}


def degrade(
    target: np.ndarray,
    profile: DegradationProfile,
    rng: np.random.Generator | None = None,
    ignore_index: int = IGNORE_INDEX,
) -> np.ndarray:
    """Produce a synthetic prediction from a ground-truth mask.

    Void pixels are passed through unchanged; they are excluded from every
    metric anyway, and inventing predictions for them would only obscure that.
    """
    if rng is None:
        rng = np.random.default_rng(0)

    target = np.asarray(target)
    pred = target.copy()
    void = target == ignore_index

    for cls in profile.drop:
        pred[target == cls] = profile.fill_for(cls)

    for cls, k in profile.erode.items():
        if cls in profile.drop or k <= 0:
            continue
        mask = target == cls
        if not mask.any():
            continue
        kept = _erode(mask, k)
        pred[mask & ~kept] = profile.fill_for(cls)

    for cls, k in profile.dilate.items():
        if k <= 0:
            continue
        mask = target == cls
        if not mask.any():
            continue
        grown = _dilate(mask, k) & ~void
        pred[grown] = cls

    if profile.noise > 0:
        flip = (rng.random(target.shape) < profile.noise) & ~void
        pred[flip] = rng.integers(0, NUM_CLASSES, size=int(flip.sum()))

    pred[void] = target[void]
    return pred.astype(target.dtype)


def profile_summary() -> list[dict]:
    """Machine-readable description of each profile, for the report."""
    return [
        {
            "name": p.name,
            "description": p.description,
            "dropped_classes": [CLASS_NAMES[c] for c in p.drop],
            "eroded_classes": {CLASS_NAMES[c]: k for c, k in p.erode.items()},
            "dilated_classes": {CLASS_NAMES[c]: k for c, k in p.dilate.items()},
            "noise": p.noise,
            "synthetic": True,
        }
        for p in PROFILES.values()
    ]
